site_name: bokbokbok doks

repo_url: https://github.com/orchardbirds/bokbokbok/
site_url: https://orchardbirds.github.io/bokbokbok/
site_description: Implementing Custom Loss Functions and Eval Metrics in LightGBM and XGBoost
site_author: Daniel Timbrell

use_directory_urls: false

nav:
  - Home: index.md
  - Getting started:
    - getting_started/install.md
  - How To:
      - Use Weighted Cross Entropy: tutorials/weighted_cross_entropy.ipynb
      - Use Weighted Focal Loss: tutorials/focal_loss.ipynb
      - Use F1 Score: tutorials/F1_score.ipynb
  - Derivations:
      - General Remarks: derivations/note.md
      - Weighted Cross Entropy: derivations/wce.md
      - Focal Loss: derivations/focal.md
      - Squared Log Error: derivations/sle.md
      - Log Cosh Error: derivations/log_cosh.md

plugins:
  - mkdocstrings:
      handlers:
          python:
            selection:
              inherited_members: true
              filters:
                - "!^Base"
                - "!^_"  # exlude all members starting with _
                - "^__init__$"  # but always include __init__ modules and methods
            rendering:
              show_root_toc_entry: false
      watch:
        - bokbokbok
  - search
  - mknotebooks:
      enable_default_jupyter_cell_styling: true
      enable_default_pandas_dataframe_styling: true

copyright: Copyright &copy; 2020

theme:
  name: material
  logo: img/bokbokbok.png
  favicon: img/bokbokbok.png
  font:
    text: Ubuntu
    code: Ubuntu Mono
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: pink
    accent: blue


markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: true