name: Publish Documentation

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: '2.0.0'  # Update to match your project

    - name: Install dependencies
      run: |
        poetry install --with dev

    - name: Install additional tools (e.g., kaleido for static image export)
      run: |
        poetry run pip install kaleido psutil

    - name: Deploy MkDocs site
      run: |
        poetry run mkdocs gh-deploy --force