name: Development
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
jobs:
  run:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [macos, ubuntu, windows]
        include:
          - build: macos
            os: macos-latest
            SKIP_LIGHTGBM: False
          - build: ubuntu
            os: ubuntu-latest
            SKIP_LIGHTGBM: False
          - build: windows
            os: windows-latest
            SKIP_LIGHTGBM: False
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python  
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      env:
        SKIP_LIGHTGBM: ${{ matrix.SKIP_LIGHTGBM }}
      run: |
        pip3 install --upgrade setuptools pip
        pip3 install ".[all]"
    - name: Run unit tests and linters
      env:
        SKIP_LIGHTGBM: ${{ matrix.SKIP_LIGHTGBM }}
      run: |
        pytest
