name: Development
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
jobs:
  run:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [ubuntu]
        include:
          - build: ubuntu
            os: ubuntu-latest
        python-version: [3.11]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python  
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip3 install --upgrade setuptools pip poetry
        pip3 poetry install --with dev
    - name: Run unit tests and linters
      run: |
        pytest tests/
    - name: Static code checking with ruff
      run: |
        ruff check
